data:
  message: '{cipher}8f9e6df5141397141ff1c88b0bfef9e1e6478115e72845fe72e065cdc66b7b97'
server:
  port: 8090
spring:
  application:
    name: test
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8081/eureka/,http://admin:admin123@localhost:8082/eureka/
    fetch-registry: true
    register-with-eureka: true